name: Run tests

# Install dependencies and run tests
on:
  push:

  workflow_dispatch:
    inputs:
      desc:
        description: 'Message'
        required: true
        default: 'Manual build'

jobs:
  build:
    name: CI check
    runs-on: ubuntu-latest
    env:
      CACHE_KEY: 'ci'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/node.env

      - name: Use Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # each workflow has its own isolated environment and they don't share cache with each other, so the key should be unique for the workflow to work properly
      - name: Check if node modules are cached
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ env.CACHE_KEY }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run format
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn format:check

      - name: Run tests
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn test

      - name: Run linters
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn lint

      - name: Run tsc
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn tsc
