export { copyTemplate } from './copyTemplate.js'
export { installDeps } from './installDeps.js'
export { replaceInFile } from './replaceInFile.js'
export { initGit } from './initGit.js'
export { addExtras } from './addExtras.js'
