name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag: ${{ github.ref }}
          body: |
            Release notes for version ${{ github.ref }}
          draft: false
